version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: tournament_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tournament_network

  nginx:
    image: nginx:alpine
    container_name: tournament_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tournament_network

  reverb:
    image: php:8.2-cli
    container_name: tournament_reverb
    working_dir: /var/www
    command: php artisan reverb:start
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - tournament_network

networks:
  tournament_network:
    driver: bridge
